const fundraisingActionTypes = {
    
    // donation list
    FETCH_DONATION_LIST:'FETCH_DONATION_LIST',
    FETCH_DONATION_LIST_SUCCESS:'FETCH_DONATION_LIST_SUCCESS',
    FETCH_DONATION_LIST_FAIL : 'FETCH_DONATION_LIST_FAIL',

    // get donation item by Id
    FETCH_DONATION:'FETCH_DONATION',
    FETCH_DONATION_FAIL:'FETCH_DONATION_FAIL',
    FETCH_DONATION_SUCCESS:'FETCH_DONATION_SUCCESS',

    // fetch common donation
    FETCH_GENERAL_DONATION:'FETCH_GENERAL_DONATION',
    FETCH_GENERAL_DONATION_SUCCESS:'FETCH_GENERAL_DONATION_SUCCESS',
    FETCH_GENERAL_DONATION_FAIL:'FETCH_GENERAL_DONATION_FAIL',
    
}
export default fundraisingActionTypes;