const homeActionTypes = {
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  SAVE_SELECTED_CLASS: 'SAVE_SELECTED_CLASS',

  FETCH_ALL_NOTIFICATION: 'FETCH_ALL_NOTIFICATION',
  FETCH_ALL_NOTIFICATION_SUCCESS: 'FETCH_ALL_NOTIFICATION_SUCCESS',
  FETCH_ALL_NOTIFICATION_FAIL: 'FETCH_ALL_NOTIFICATION_FAIL',

  // student attendance in calendar screens
  FETCH_ATTENDANCE_CALENDAR_STUDENT: 'FETCH_ATTENDANCE_CALENDAR_STUDENT',
  FETCH_ATTENDANCE_CALENDAR_STUDENT_FAIL:
    'FETCH_ATTENDANCE_CALENDAR_STUDENT_FAIL',
  FETCH_ATTENDANCE_CALENDAR_STUDENT_SUCCESS:
    'FETCH_ATTENDANCE_CALENDAR_STUDENT_SUCCESS',

  // leave type in calendar screens
  FETCH_LEAVE_TYPE: 'FETCH_LEAVE_TYPE',
  FETCH_LEAVE_TYPE_FAIL: 'FETCH_LEAVE_TYPE_FAIL',
  FETCH_LEAVE_TYPE_SUCCESS: 'FETCH_LEAVE_TYPE_SUCCESS',
  // Attendant alert in calendar screens
  MAKE_ATTENDANT_ALERT: 'MAKE_ATTENDANT_ALERT',
  MAKE_ATTENDANT_ALERT_FAIL: 'MAKE_ATTENDANT_ALERT_FAIL',
  MAKE_ATTENDANT_ALERT_SUCCESS: 'MAKE_ATTENDANT_ALERT_SUCCESS',

  // merchandise screen
  FETCH_MERCHANDISE_TYPE: 'FETCH_MERCHANDISE_TYPE',
  FETCH_MERCHANDISE_TYPE_SUCCESS: 'FETCH_MERCHANDISE_TYPE_SUCCESS',
  FETCH_MERCHANDISE_TYPE_FAIL: 'FETCH_MERCHANDISE_TYPE_FAIL',

  // class student attendance
  FETCH_STUDENT_ATTENDANCE_BY_CLASS: 'FETCH_STUDENT_ATTENDANCE_BY_CLASS',
  FETCH_STUDENT_ATTENDANCE_BY_CLASS_SUCCESS:
    'FETCH_STUDENT_ATTENDANCE_BY_CLASS_SUCCESS',
  FETCH_STUDENT_ATTENDANCE_BY_CLASS_FAIL:
    'FETCH_STUDENT_ATTENDANCE_BY_CLASS_FAIL',

  // calendar view of events + schedule
  FETCH_CALENDAR_VIEW_OF_EVENTS_OR_SCHEDULES:
    'FETCH_CALENDAR_VIEW_OF_EVENTS_OR_SCHEDULES',
  FETCH_CALENDAR_VIEW_OF_EVENTS_OR_SCHEDULES_SUCCESS:
    'FETCH_CALENDAR_VIEW_OF_EVENTS_OR_SCHEDULES_SUCCESS',
  FETCH_CALENDAR_VIEW_OF_EVENTS_OR_SCHEDULES_FAIL:
    'FETCH_CALENDAR_VIEW_OF_EVENTS_OR_SCHEDULES_FAIL',

  // comms screens
  GET_MESSAGES_BETWEEN_USERS: 'GET_MESSAGES_BETWEEN_USERS',
  GET_MESSAGES_BETWEEN_USERS_SUCCESS: 'GET_MESSAGES_BETWEEN_USERS_SUCCESS',
  GET_MESSAGES_BETWEEN_USERS_FAIL: 'GET_MESSAGES_BETWEEN_USERS_FAIL',

  SEND_MESSAGES_BETWEEN_USERS: 'SEND_MESSAGES_BETWEEN_USERS',
  SEND_MESSAGES_BETWEEN_USERS_SUCCESS: 'SEND_MESSAGES_BETWEEN_USERS_SUCCESS',
  SEND_MESSAGES_BETWEEN_USERS_FAIL: 'SEND_MESSAGES_BETWEEN_USERS_FAIL',

  FETCH_CONTACT_LIST: 'FETCH_CONTACT_LIST',
  FETCH_CONTACT_LIST_SUCCESS: 'FETCH_CONTACT_LIST_SUCCESS',
  FETCH_CONTACT_LIST_FAIL: 'FETCH_CONTACT_LIST_FAIL',

  GET_ROOM_LIST: 'GET_ROOM_LIST',
  GET_ROOM_LIST_SUCCESS: 'GET_ROOM_LIST_SUCCESS',
  GET_ROOM_LIST_FAIL: 'GET_ROOM_LIST_FAIL',

  DELETE_ROOM: 'DELETE_ROOM',
  DELETE_ROOM_SUCCESS: 'DELETE_ROOM_SUCCESS',
  DELETE_ROOM_FAIL: 'DELETE_ROOM_FAIL',

  // get schedule info
  FETCH_SCHEDULE_INFO: 'FETCH_SCHEDULE_INFO',
  FETCH_SCHEDULE_INFO_FAIL: 'FETCH_SCHEDULE_INFO_FAIL',
  FETCH_SCHEDULE_INFO_SUCCESS: 'FETCH_SCHEDULE_INFO_SUCCESS',

  // get schedule item
  FETCH_SCHEDULE_ITEM: 'FETCH_SCHEDULE_ITEM',
  FETCH_SCHEDULE_ITEM_SUCCESS: 'FETCH_SCHEDULE_ITEM_SUCCESS',
  FETCH_SCHEDULE_ITEM_FAIL: 'FETCH_SCHEDULE_ITEM_FAIL',

  // all events
  FETCH_ALL_EVENTS: 'FETCH_ALL_EVENTS',
  FETCH_ALL_EVENTS_SUCCESS: 'FETCH_ALL_EVENTS_SUCCESS',
  FETCH_ALL_EVENTS_FAIL: 'FETCH_ALL_EVENTS_FAIL',

  // get event data by id
  FETCH_EVENT_DATA: 'FETCH_EVENT_DATA',
  FETCH_EVENT_DATA_SUCCESS: 'FETCH_EVENT_DATA_SUCCESS',
  FETCH_EVENT_DATA_FAIL: 'FETCH_EVENT_DATA_FAIL',

  //get event people data by id
  FETCH_EVENT_PEOPLE_DATA: 'FETCH_EVENT_PEOPLE_DATA',
  FETCH_EVENT_PEOPLE_DATA_SUCCESS: 'FETCH_EVENT_PEOPLE_DATA_SUCCESS',
  FETCH_EVENT_PEOPLE_DATA_FAIL: 'FETCH_EVENT_PEOPLE_DATA_FAIL',

  RESET_EVENT_PEOPLE: 'RESET_EVENT_PEOPLE',

  // get facilitator student attendance detail
  FETCH_STUDENT_ATTENDANCE_DETAILS: 'FETCH_STUDENT_ATTENDANCE_DETAILS',
  FETCH_STUDENT_ATTENDANCE_DETAILS_FAIL:
    'FETCH_STUDENT_ATTENDANCE_DETAILS_FAIL',
  FETCH_STUDENT_ATTENDANCE_DETAILS_SUCCESS:
    'FETCH_STUDENT_ATTENDANCE_DETAILS_SUCCESS',

  // post facilitator student attendance detail
  MAKE_STUDENT_ATTENDANCE_DETAILS: 'MAKE_STUDENT_ATTENDANCE_DETAILS',
  MAKE_STUDENT_ATTENDANCE_DETAILS_UPDATE:
    'MAKE_STUDENT_ATTENDANCE_DETAILS_UPDATE',
  MAKE_STUDENT_ATTENDANCE_DETAILS_SUCCESS:
    'MAKE_STUDENT_ATTENDANCE_DETAILS_SUCCESS',
  MAKE_STUDENT_ATTENDANCE_DETAILS_FAIL: 'MAKE_STUDENT_ATTENDANCE_DETAILS_FAIL',

  // translate message
  GET_TRANSLATE: 'GET_TRANSLATE',
  GET_TRANSLATE_SUCCESS: 'GET_TRANSLATE_SUCCESS',
  GET_TRANSLATE_FAIL: 'GET_TRANSLATE_FAIL',
  SET_TRANSLATE: 'SET_TRANSLATE ',

  // mark as read notification
  MAKE_NOTIFICATION_READ: 'MAKE_NOTIFICATION_READ',
  MAKE_NOTIFICATION_READ_SUCCESS: 'MAKE_NOTIFICATION_READ_SUCCESS',
  MAKE_NOTIFICATION_READ_FAIL: 'MAKE_NOTIFICATION_READ_FAIL',

  // get merchandise data by merchandise type
  FETCH_MERCHANDISE_DATA: 'FETCH_MERCHANDISE_DATA',
  FETCH_MERCHANDISE_DATA_FAIL: 'FETCH_MERCHANDISE_DATA_FAIL',
  FETCH_MERCHANDISE_DATA_SUCCESS: 'FETCH_MERCHANDISE_DATA_SUCCESS',

  // get all merchandise data
  FETCH_ALL_MERCHANDISE_DATA: 'FETCH_ALL_MERCHANDISE_DATA',
  FETCH_ALL_MERCHANDISE_DATA_SUCCESS: 'FETCH_ALL_MERCHANDISE_DATA_SUCCESS',
  FETCH_ALL_MERCHANDISE_DATA_FAIL: 'FETCH_ALL_MERCHANDISE_DATA_FAIL',

  // get merchandise details
  FETCH_MERCHANDISE_DETAILS: 'FETCH_MERCHANDISE_DETAILS',
  FETCH_MERCHANDISE_DETAILS_FAIL: 'FETCH_MERCHANDISE_DETAILS_FAIL',
  FETCH_MERCHANDISE_DETAILS_SUCCESS: 'FETCH_MERCHANDISE_DETAILS_SUCCESS',

  // add to cart
  ADD_TO_CART: 'ADD_TO_CART',

  // refresh state
  SET_DATA: 'SET_DATA',

  // get all newsfeeds
  FETCH_ALL_NEWSFEEDS: 'FETCH_ALL_NEWSFEEDS',
  FETCH_ALL_NEWSFEEDS_SUCCESS: 'FETCH_ALL_NEWSFEEDS_SUCCESS',
  FETCH_ALL_NEWSFEEDS_FAIL: 'FETCH_ALL_NEWSFEEDS_FAIL',

  FOUND_NEW_POST: 'FOUND_NEW_POST',

  // get ordered merchandise data
  FETCH_ORDERED_MERCHANDISE_DATA: 'FETCH_ORDERED_MERCHANDISE_DATA',
  FETCH_ORDERED_MERCHANDISE_DATA_SUCCESS:
    'FETCH_ORDERED_MERCHANDISE_DATA_SUCCESS',
  FETCH_ORDERED_MERCHANDISE_DATA_FAIL: 'FETCH_ORDERED_MERCHANDISE_DATA_FAIL',

  // post method , update order status with facilitator
  CHANGE_ORDERED_MERCHANDISE_STATUS: 'CHANGE_ORDERED_MERCHANDISE_STATUS',
  CHANGE_ORDERED_MERCHANDISE_STATUS_FAIL:
    'CHANGE_ORDERED_MERCHANDISE_STATUS_FAIL',
  CHANGE_ORDERED_MERCHANDISE_STATUS_SUCCESS:
    'CHANGE_ORDERED_MERCHANDISE_STATUS_SUCCESS',

  // post method, order the merchandise by parent
  ORDER_MERCHANDISE: 'ORDER_MERCHANDISE',
  ORDER_MERCHANDISE_FAIL: 'ORDER_MERCHANDISE_FAIL',
  ORDER_MERCHANDISE_SUCCESS: 'ORDER_MERCHANDISE_SUCCESS',

  // clear fetch merchandise details data
  CLEAR_MERCHANDISE_DETAILS_DATA: 'CLEAR_MERCHANDISE_DETAILS_DATA',

  // update ordered merchandise data is_select
  UPDATE_ORDERED_MERCHANDISE_DATA_IS_SELECT:
    'UPDATE_ORDERED_MERCHANDISE_DATA_IS_SELECT',

  //To get future attendance details
  FETCH_FUTURE_ATTENDANCE_DETAIL: 'FETCH_FUTURE_ATTENDANCE_DETAIL',
  FETCH_FUTURE_ATTENDANCE_DETAIL_SUCCESS:
    'FETCH_FUTURE_ATTENDANCE_DETAIL_SUCCESS',
  FETCH_FUTURE_ATTENDANCE_DETAIL_FAIL: 'FETCH_FUTURE_ATTENDANCE_DETAIL_FAIL',

  //update future attendance
  MAKE_ATTENDANT_ALERT_UPDATE: 'MAKE_ATTENDANT_ALERT_UPDATE',

  // GET ordered list by parents
  GET_ORDERED_LIST_FOR_PARENTS: 'GET_ORDERED_LIST_FOR_PARENTS',
  GET_ORDERED_LIST_FOR_PARENTS_SUCCESS: 'GET_ORDERED_LIST_FOR_PARENTS_SUCCESS',
  GET_ORDERED_LIST_FOR_PARENTS_FAIL: 'GET_ORDERED_LIST_FOR_PARENTS_FAIL',

  //parent event registration
  MAKE_PARENT_EVENT_REGISTER: 'MAKE_PARENT_EVENT_REGISTER',
  MAKE_PARENT_EVENT_REGISTER_UPDATE: 'MAKE_PARENT_EVENT_REGISTER_UPDATE',
  MAKE_PARENT_EVENT_REGISTER_SUCCESS: 'MAKE_PARENT_EVENT_REGISTER_SUCCESS',
  MAKE_PARENT_EVENT_REGISTER_FAIL: 'MAKE_PARENT_EVENT_REGISTER_FAIL',

  //parent register event by filter parent id and parent id
  FETCH_ALL_REGISTER_PARENTID_EVENT: 'FETCH_ALL_REGISTER_PARENTID_EVENT',
  FETCH_ALL_REGISTER_PARENTID_EVENT_SUCCESS:
    'FETCH_ALL_REGISTER_PARENTID_EVENT_SUCCESS',
  FETCH_ALL_REGISTER_PARENTID_EVENT_FAIL:
    'FETCH_ALL_REGISTER_PARENTID_EVENT_FAIL',

  // Post Newsfeed
  POST_NEWSFEED: 'POST_NEWSFEED',
  POST_NEWSFEED_SUCCESS: 'POST_NEWSFEED_SUCCESS',
  POST_NEWSFEED_FAIL: 'POST_NEWSFEED_FAIL',

  //parent alert on attendance for chidren to facilitator
  FETCH_ATTENDANCE_ALERT: 'FETCH_ATTENDANCE_ALERT',
  FETCH_ATTENDANCE_ALERT_SUCCESS: 'FETCH_ATTENDANCE_ALERT_SUCCESS',
  FETCH_ATTENDANCE_ALERT_FAIL: 'FETCH_ATTENDANCE_ALERT_FAIL',

  // get holidays
  FETCH_HOLIDAYS_DATE: 'FETCH_HOLIDAYS_DATE',
  FETCH_HOLIDAYS_DATE_FAIL: 'FETCH_HOLIDAYS_DATE_FAIL',
  FETCH_HOLIDAYS_DATE_SUCCESS: 'FETCH_HOLIDAYS_DATE_SUCCESS',

  //send message to mulitple parents
  MAKE_MULTIPLE_PARENT_MESSAGES: 'MAKE_MULTIPLE_PARENT_MESSAGES',
  MAKE_MULTIPLE_PARENT_MESSAGES_SUCCESS:
    'MAKE_MULTIPLE_PARENT_MESSAGES_SUCCESS',
  MAKE_MULTIPLE_PARENT_MESSAGES_FAIL: 'MAKE_MULTIPLE_PARENT_MESSAGES_FAIL',

  //get holidays
  FETCH_HOLIDAY: 'FETCH_HOLIDAY',
  FETCH_HOLIDAY_SUCCESS: 'FETCH_HOLIDAY_SUCCESS',
  FETCH_HOLIDAY_FAIL: 'FETCH_HOLIDAY_FAIL',

  // get schedule colors
  FETCH_SCHEDULE_COLORS: 'FETCH_SCHEDULE_COLORS',
  FETCH_SCHEDULE_COLORS_FAIL: 'FETCH_SCHEDULE_COLORS_FAIL',
  FETCH_SCHEDULE_COLORS_SUCCESS: 'FETCH_SCHEDULE_COLORS_SUCCESS',

  // change succesful newfeed var
  CHANGE_SUCCESSFUL_NEWSFEED: 'CHANGE_SUCCESSFUL_NEWSFEED',

  // check notification is read
  CHECK_NOTIFICATION_IS_READ: 'CHECK_NOTIFICATION_IS_READ',
  CHECK_NOTIFICATION_IS_READ_SUCCESS: 'CHECK_NOTIFICATION_IS_READ_SUCCESS',
  CHECK_NOTIFICATION_IS_READ_FAIL: 'CHECK_NOTIFICATION_IS_READ_FAIL',

  // HIDE NOTIFICATION
  HIDE_NOTIFICATION_ITEM: 'HIDE_NOTIFICATION_ITEM',
  HIDE_NOTIFICATION_ITEM_FAIL: 'HIDE_NOTIFICATION_ITEM_FAIL',
  HIDE_NOTIFICATION_ITEM_SUCCESS: 'HIDE_NOTIFICATION_ITEM_SUCCESS',

  // send temporary between users
  CHAT_MESSAGE_BETWEEN_USERS: 'CHAT_MESSAGE_BETWEEN_USERS',

  //
  SET_SCREEN_OPENING: 'SET_SCREEN_OPENING',

  // initializing
  SET_INITIALIZING: 'SET_INITIALIZING',

  // form api get
  FETCH_DIGITAL_FORMS: 'FETCH_FORMS',
  FETCH_DIGITAL_FORMS_FAIL: 'FETCH_DIGITAL_FORMS_FAIL',
  FETCH_DIGITAL_FORMS_SUCCESS: 'FETCH_DIGITAL_FORMS_SUCCESS',

  // form api post
  POST_FORMS: 'POST_FORMS',
  POST_FORMS_FAIL: 'POST_FORMS_FAIL',
  POST_FORMS_SUCCESS: 'POST_FORMS_SUCCESS',

  // upload s3
  UPLOAD_S3: 'UPLOAD_S3',
  UPLOAD_S3_FAIL: 'UPLOAD_S3_FAIL',

  // form api get
  FETCH_DIGITAL_FORMS: 'FETCH_FORMS',
  FETCH_DIGITAL_FORMS_FAIL: 'FETCH_DIGITAL_FORMS_FAIL',
  FETCH_DIGITAL_FORMS_SUCCESS: 'FETCH_DIGITAL_FORMS_SUCCESS',

  // read comms message
  READ_COMMS_MESSAGE: 'READ_COMMS_MESSAGE',
  READ_COMMS_MESSAGE_FAIL: 'READ_COMMS_MESSAGE_FAIL',
  READ_COMMS_MESSAGE_SUCCESS: 'READ_COMMS_MESSAGE_SUCCESS',

  // count of item cart
  SET_COUNT_OF_CART_ITEMS: 'SET_COUNT_OF_CART_ITEMS',

  // selected date in home screen
  SET_SELECTED_DATE: 'SET_SELECTED_DATE',

  // get event people data
  SET_EVENT_PEOPLE_DATA: 'SET_EVENT_PEOPLE_DATA',

  // fetch all events for dots
  FETCH_ALL_EVENTS_FOR_DOTS:'FETCH_ALL_EVENTS_FOR_DOTS',
  FETCH_ALL_EVENTS_FOR_DOTS_FAIL:'FETCH_ALL_EVENTS_FOR_DOTS_FAIL',
  FETCH_ALL_EVENTS_FOR_DOTS_SUCCESS:'FETCH_ALL_EVENTS_FOR_DOTS_SUCCESS',

  // fetch all attendance for dots by student in calendar
  FETCH_ALL_ATTENDANCE_FOR_DOTS:'FETCH_ALL_ATTENDANCE_FOR_DOTS',
  FETCH_ALL_ATTENDANCE_FOR_DOTS_FAIL:'FETCH_ALL_ATTENDANCE_FOR_DOTS_FAIL',
  FETCH_ALL_ATTENDANCE_FOR_DOTS_SUCCESS:'FETCH_ALL_ATTENDANCE_FOR_DOTS_SUCCESS',

  // get attendance details by student id 
  GET_ATTENDANCE_DETAILS_OF_STUDENT:'GET_ATTENDANCE_DETAILS_OF_STUDENT',
  GET_ATTENDANCE_DETAILS_OF_STUDENT_FAIL:'GET_ATTENDANCE_DETAILS_OF_STUDENT_FAIL',
  GET_ATTENDANCE_DETAILS_OF_STUDENT_SUCCESS:'GET_ATTENDANCE_DETAILS_OF_STUDENT_SUCCESS',


  // fetch attendance for dots by class 
  FETCH_ATTENDANCE_FOR_DOTS_BY_CLASS:'FETCH_ATTENDANCE_FOR_DOTS_BY_CLASS',
  FETCH_ATTENDANCE_FOR_DOTS_BY_CLASS_SUCCESS:'FETCH_ATTENDANCE_FOR_DOTS_BY_CLASS_SUCCESS',
  FETCH_ATTENDANCE_FOR_DOTS_BY_CLASS_FAIL:'FETCH_ATTENDANCE_FOR_DOTS_BY_CLASS_FAIL',

  // List all parents with attend_status within the class_id of event.
  FETCH_ALL_DATA_ATTENDED_BY_EVENT:'FETCH_ALL_DATA_ATTENDED_BY_EVENT',
  FETCH_ALL_DATA_ATTENDED_BY_EVENT_FAIL:'FETCH_ALL_DATA_ATTENDED_BY_EVENT_FAIL',
  FETCH_ALL_DATA_ATTENDED_BY_EVENT_SUCCESS:'FETCH_ALL_DATA_ATTENDED_BY_EVENT_SUCCESS',

  // note data 
  FETCH_NOTE_DATA:'FETCH_NOTE_DATA',
  FETCH_NOTE_DATA_SUCCESS:'FETCH_NOTE_DATA_SUCCESS',
  FETCH_NOTE_DATA_FAIL:'FETCH_NOTE_DATA_FAIL',

  // get room id between user
  GET_ROOM_ID_BETWEEN_USERS:'GET_ROOM_ID_BETWEEN_USERS',
  GET_ROOM_ID_BETWEEN_USERS_FAIL:'GET_ROOM_ID_BETWEEN_USERS_FAIL',
  GET_ROOM_ID_BETWEEN_USERS_SUCCESS:'GET_ROOM_ID_BETWEEN_USERS_SUCCESS',

  // get unregistered parent data by event id
  GET_UNREGISTERED_PARENT_BY_EVENT:'GET_UNREGISTERED_PARENT_BY_EVENT',
  GET_UNREGISTERED_PARENT_BY_EVENT_FAIL:'GET_UNREGISTERED_PARENT_BY_EVENT_FAIL',
  GET_UNREGISTERED_PARENT_BY_EVENT_SUCCESS:'GET_UNREGISTERED_PARENT_BY_EVENT_SUCCESS',

  // tranlation for comms message
  SET_TRANSLATE_MESSAGES:'SET_TRANSLATE_MESSAGES',
  SET_TRANSLATE_MESSAGES_FAIL:'SET_TRANSLATE_MESSAGES_FAIL',
  SET_TRANSLATE_MESSAGES_SUCCESS:'SET_TRANSLATE_MESSAGES_SUCCESS',

  // GET FORM DETAILS
  GET_FORM_DETAILS_DATA:'GET_FORM_DETAILS_DATA',
  GET_FORM_DETAILS_DATA_FAIL:'GET_FORM_DETAILS_DATA_FAIL',
  GET_FORM_DETAILS_DATA_SUCCESS:'GET_FORM_DETAILS_DATA_SUCCESS',

  // Delete newsfeeds
  DELETE_NEWSFEED:'DELETE_NEWSFEED',
  DELETE_NEWSFEED_FAIL:'DELETE_NEWSFEED_FAIL',
  DELETE_NEWSFEED_SUCCESS:'DELETE_NEWSFEED_SUCCESS',

  // get Delivered Merchandise Data
  GET_DELIVERED_MERCHANDISE_DATA:'GET_DELIVERED_MERCHANDISE_DATA',
  GET_DELIVERED_MERCHANDISE_DATA_FAIL:'GET_DELIVERED_MERCHANDISE_DATA_FAIL',
  GET_DELIVERED_MERCHANDISE_DATA_SUCCESS:'GET_DELIVERED_MERCHANDISE_DATA_SUCCESS',

  // 
  UPDATE_MERCHANDISE_DATA_ORDERED_DELIVERED:'UPDATE_MERCHANDISE_DATA_ORDERED_DELIVERED',

  // get pending payment ordered lists of parents
  PENDING_PAYMENT_ORDERED_LISTS_OF_PARENT:'PENDING_PAYMENT_ORDERED_LISTS_OF_PARENT',
  PENDING_PAYMENT_ORDERED_LISTS_OF_PARENT_FAIL:'PENDING_PAYMENT_ORDERED_LISTS_OF_PARENT_FAIL',
  PENDING_PAYMENT_ORDERED_LISTS_OF_PARENT_SUCCESS:'PENDING_PAYMENT_ORDERED_LISTS_OF_PARENT_SUCCESS',

  PAYMENT_VERIFICATION_ORDERED_LISTS_OF_PARENT:'PAYMENT_VERIFICATION_ORDERED_LISTS_OF_PARENT',
  PAYMENT_VERIFICATION_ORDERED_LISTS_OF_PARENT_FAIL:'PAYMENT_VERIFICATION_ORDERED_LISTS_OF_PARENT_FAIL',
  PAYMENT_VERIFICATION_ORDERED_LISTS_OF_PARENT_SUCCESS:'PAYMENT_VERIFICATION_ORDERED_LISTS_OF_PARENT_SUCCESS',

  PAID_ORDERED_LISTS_OF_PARENT:'PAID_ORDERED_LISTS_OF_PARENT',
  PAID_ORDERED_LISTS_OF_PARENT_FAIL:'PAID_ORDERED_LISTS_OF_PARENT_FAIL',
  PAID_ORDERED_LISTS_OF_PARENT_SUCCESS:'PAID_ORDERED_LISTS_OF_PARENT_SUCCESS',

  DELIVERED_ORDERED_LISTS_OF_PARENT:'DELIVERED_ORDERED_LISTS_OF_PARENT',
  DELIVERED_ORDERED_LISTS_OF_PARENT_FAIL:'DELIVERED_ORDERED_LISTS_OF_PARENT_FAIL',
  DELIVERED_ORDERED_LISTS_OF_PARENT_SUCCESS:'DELIVERED_ORDERED_LISTS_OF_PARENT_SUCCESS',

  CANCELLED_ORDERED_LISTS_OF_PARENT:'CANCELLED_ORDERED_LISTS_OF_PARENT',
  CANCELLED_ORDERED_LISTS_OF_PARENT_FAIL:'CANCELLED_ORDERED_LISTS_OF_PARENT_FAIL',
  CANCELLED_ORDERED_LISTS_OF_PARENT_SUCCESS:'CANCELLED_ORDERED_LISTS_OF_PARENT_SUCCESS',

  SUBMIT_ORDER_MERCHANDISE:'SUBMIT_ORDER_MERCHANDISE',
  SUBMIT_ORDER_MERCHANDISE_FAIL:'SUBMIT_ORDER_MERCHANDISE_FAIL',
  SUBMIT_ORDER_MERCHANDISE_SUCCESS:'SUBMIT_ORDER_MERCHANDISE_SUCCESS',

  // GET SCHEDULE TYPPES
  GET_SCHEDULE_TYPES:'GET_SCHEDULE_TYPES',
  GET_SCHEDULE_TYPES_FAIL:'GET_SCHEDULE_TYPES_FAIL',
  GET_SCHEDULE_TYPES_SUCCESS:'GET_SCHEDULE_TYPES_SUCCESS',

  FETCH_DASHBOARD_CAROUSEL:'FETCH_DASHBOARD_CAROUSEL',
  FETCH_DASHBOARD_CAROUSEL_SUCCESS:'FETCH_DASHBOARD_CAROUSEL_SUCCESS',
  FETCH_DASHBOARD_CAROUSEL_FAIL:'FETCH_DASHBOARD_CAROUSEL_FAIL',
  
};

export default homeActionTypes;
