const paymentActionTypes = {

    CREATE_PAYMENT:'CREATE_PAYMENT',
    CREATE_PAYMENT_SUCCESS:'CREATE_PAYMENT_SUCCESS',
    CREATE_PAYMENT_FAIL:'CREATE_PAYMENT_FAIL',

    GET_COMPLETE_PAYMENT_STATUS:'GET_COMPLETE_PAYMENT_STATUS',
    GET_COMPLETE_PAYMENT_STATUS_SUCCESS:'GET_COMPLETE_PAYMENT_STATUS_SUCCESS',
    GET_COMPLETE_PAYMENT_STATUS_FAIL:'GET_COMPLETE_PAYMENT_STATUS_FAIL',

    GET_PAYMENT_STATUS:'GET_PAYMENT_STATUS',
    GET_PAYMENT_STATUS_FAIL:'GET_PAYMENT_STATUS_FAIL',
    GET_PAYMENT_STATUS_SUCCESS:'GET_PAYMENT_STATUS_SUCCESS',

    CREATE_PAYMENT_WITH_PAYNOW:'CREATE_PAYMENT_WITH_PAYNOW',
    CREATE_PAYMENT_WITH_PAYNOW_SUCCESS:'CREATE_PAYMENT_WITH_PAYNOW_SUCCESS',
    CREATE_PAYMENT_WITH_PAYNOW_FAIL:'CREATE_PAYMENT_WITH_PAYNOW_FAIL',

    PAYMENT_MERCHANDISE_WITH_PAYNOW:'PAYMENT_MERCHANDISE_WITH_PAYNOW',
    PAYMENT_MERCHANDISE_WITH_PAYNOW_SUCCESS:'PAYMENT_MERCHANDISE_WITH_PAYNOW_SUCCESS',
    PAYMENT_MERCHANDISE_WITH_PAYNOW_FAIL:'PAYMENT_MERCHANDISE_WITH_PAYNOW_FAIL',

    CREATE_PAYMENT_MERCHANDISE: 'CREATE_PAYMENT_MERCHANDISE',
    CREATE_PAYMENT_MERCHANDISE_SUCCESS: 'CREATE_PAYMENT_MERCHANDISE_SUCCESS',
    CREATE_PAYMENT_MERCHANDISE_FAIL: 'CREATE_PAYMENT_MERCHANDISE_FAIL',

    GET_COMPLETE_PAYMENT_MERCHANDISE_STATUS:'GET_COMPLETE_PAYMENT_MERCHANDISE_STATUS',
    GET_COMPLETE_PAYMENT_MERCHANDISE_STATUS_SUCCESS:'GET_COMPLETE_PAYMENT_MERCHANDISE_STATUS_SUCCESS',
    GET_COMPLETE_PAYMENT_MERCHANDISE_STATUS_FAIL:'GET_COMPLETE_PAYMENT_MERCHANDISE_STATUS_FAIL',

    GET_PAYMENT_MERCHANDISE_STATUS:'GET_PAYMENT_MERCHANDISE_STATUS',
    GET_PAYMENT_MERCHANDISE_STATUS_FAIL:'GET_PAYMENT_MERCHANDISE_STATUS_FAIL',
    GET_PAYMENT_MERCHANDISE_STATUS_SUCCESS:'GET_PAYMENT_MERCHANDISE_STATUS_SUCCESS',

    SEND_TRANS_REF: 'SEND_TRANS_REF',
    SEND_TRANS_REF_FAIL: 'SEND_TRANS_REF_FAIL',
    SEND_TRANS_REF_SUCCESS: 'SEND_TRANS_REF_SUCCESS',

    CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYPAL:'CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYPAL',
    CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYPAL_FAIL:'CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYPAL_FAIL',
    CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYPAL_SUCCESS:'CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYPAL_SUCCESS',

    CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYNOW:'CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYNOW',
    CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYNOW_FAIL:'CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYNOW_FAIL',
    CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYNOW_SUCCESS:'CREATE_PAYMENT_FOR_MERCHANDISE_WITH_PAYNOW_SUCCESS',
    
}

export default paymentActionTypes;