const userActionTypes = {
    
    // student Info
    FETCH_STUDENT_INFO:'FETCH_STUDENT_INFO',
    FETCH_STUDENT_INFO_SUCCESS:'FETCH_STUDENT_INFO_SUCCESS',
    FETCH_STUDENT_INFO_FAIL : 'FETCH_STUDENT_INFO_FAIL',
    
    //user setting
    SET_SETTING : "SET_SETTING",
    SET_SETTING_SUCCESS : "SET_SETTING_SUCCESS",
    SET_SETTING_FAIL : "SET_SETTING_FAIL",

    //fetch user setting 
    FETCH_SETTING : "FETCH_SETTING",
    FETCH_SETTING_SUCCESS : "FETCH_SETTING_SUCCESS",
    FETCH_SETTING_FAIL : "FETCH_SETTING_FAIL",

    CHECK_USER:'CHECK_USER',
    CHECK_USER_DONE:'CHECK_USER_DONE',
    CHECK_USER_FAIL:'CHECK_USER_FAIL',

    // update facilitator
    UPDATE_FACILITATOR_INFO:'UPDATE_FACILITATOR_INFO',
    UPDATE_FACILITATOR_INFO_FAIL:'UPDATE_FACILITATOR_INFO_FAIL',
    UPDATE_FACILITATOR_INFO_SUCCESS:'UPDATE_FACILITATOR_INFO_SUCCESS',

    // UPDATE PARENT
    UPDATE_PARENT_INFO:'UPDATE_PARENT_INFO',
    UPDATE_PARENT_INFO_SUCCESS:'UPDATE_PARENT_INFO_SUCCESS',
    UPDATE_PARENT_INFO_FAIL:'UPDATE_PARENT_INFO_FAIL',

    // UPDATE PASSWORD AFRER LOGIN
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_PASSWORD_SUCCESS:'UPDATE_PASSWORD_SUCCESS',
    UPDARE_PASSWORD_FAIL: 'UPDARE_PASSWORD_FAIL'
}
export default userActionTypes;